REMOTE_STYLES = r"""
<style>
  .remote-page { margin-top: 18px; }
  .remote-page .eyebrow, .remote-page .section-label, .remote-page .remote-form label { text-transform: none; }
  .remote-page[hidden] { display: none; }
  .remote-hero { display: grid; grid-template-columns: minmax(0,1.3fr) minmax(300px,.7fr); border: 1px solid var(--line); background: var(--paper); box-shadow: var(--shadow); }
  .remote-copy { min-height: 310px; padding: 46px; border-right: 1px solid var(--line); background: linear-gradient(130deg,transparent 0 72%,rgba(215,228,85,.38) 72%); }
  .remote-copy h1 { margin: 16px 0 12px; font: 800 clamp(50px,7vw,92px)/.84 "Iowan Old Style",serif; letter-spacing: -.055em; }
  .remote-copy p { max-width: 700px; color: var(--muted); line-height: 1.7; }
  .remote-boundary { padding: 34px; background: var(--ink); color: var(--paper); }
  .remote-boundary strong { display: block; margin: 14px 0; color: var(--acid); font: 800 24px "Iowan Old Style",serif; }
  .remote-boundary p { color: #aaa99f; font-size: 11px; line-height: 1.65; }
  .remote-section-tabs { position: sticky; top: 10px; z-index: 8; display: grid; grid-template-columns: repeat(3,minmax(0,1fr)); gap: 1px; margin-top: 14px; border: 1px solid var(--line); background: var(--line); box-shadow: var(--shadow); }
  .remote-section-tab { display: grid; grid-template-columns: auto minmax(0,1fr) auto; gap: 11px; align-items: center; min-width: 0; min-height: 68px; border: 0; background: #e7e0d2; color: var(--ink); padding: 12px 16px; text-align: left; cursor: pointer; }
  .remote-section-tab:hover { background: #f6f0e5; }
  .remote-section-tab[aria-selected="true"] { background: var(--ink); color: var(--paper); }
  .remote-section-tab:focus-visible { position: relative; z-index: 1; outline: 3px solid var(--signal); outline-offset: -3px; }
  .remote-section-tab-icon { display: grid; place-items: center; width: 32px; height: 32px; border: 1px solid currentColor; font: 900 11px monospace; }
  .remote-section-tab-copy { min-width: 0; }
  .remote-section-tab-copy small, .remote-section-tab-copy strong { display: block; }
  .remote-section-tab-copy small { margin-bottom: 3px; opacity: .6; font: 800 7px monospace; letter-spacing: .08em; text-transform: uppercase; }
  .remote-section-tab-copy strong { overflow: hidden; font: 800 16px "Iowan Old Style",serif; text-overflow: ellipsis; white-space: nowrap; }
  .remote-section-tab-count { min-width: 32px; border: 1px solid currentColor; padding: 6px 7px; font: 900 8px monospace; text-align: center; }
  .remote-section-tab[aria-selected="true"] .remote-section-tab-count { background: var(--acid); color: var(--ink); }
  .remote-section-panel[hidden] { display: none; }
  .remote-grid { display: grid; grid-template-columns: 1fr; gap: 14px; margin-top: 14px; }
  .remote-card { border: 1px solid var(--line); background: var(--paper); padding: 22px; box-shadow: var(--shadow); }
  .remote-card-head { display: flex; justify-content: space-between; gap: 16px; align-items: start; }
  .remote-card h2 { margin: 4px 0 14px; font: 800 28px "Iowan Old Style",serif; }
  .remote-state { border: 1px solid var(--ink); background: var(--paper-deep); padding: 6px 8px; font: 900 8px monospace; }
  .remote-state.ready { background: var(--acid); }
  .remote-state.mount_missing, .remote-state.bridge_read_only { background: var(--signal); color: white; }
  .remote-form { display: grid; grid-template-columns: 1fr 1fr; gap: 9px; }
  .remote-form label { display: grid; gap: 6px; color: var(--muted); font: 800 8px monospace; text-transform: uppercase; }
  .remote-form label.wide { grid-column: 1/-1; }
  .remote-form input { min-width: 0; border: 1px solid var(--line); background: #fbf6ec; padding: 10px; }
  .remote-check { display: flex !important; align-items: center; grid-template-columns: auto 1fr; }
  .remote-check input { width: auto; }
  .remote-actions { display: flex; flex-wrap: wrap; gap: 7px; margin-top: 12px; }
  .remote-actions button { border: 1px solid var(--ink); background: transparent; padding: 9px 10px; font: 900 8px monospace; }
  .remote-actions button.primary { border-color: var(--signal); background: var(--signal); color: white; }
  .remote-message { min-height: 40px; margin-top: 12px; border-left: 4px solid var(--acid); background: #e2dccd; padding: 9px 11px; font: 8px/1.55 monospace; }
  .remote-tasks { margin-top: 14px; border: 1px solid var(--line); background: var(--paper); box-shadow: var(--shadow); }
  .remote-tasks-head { display: flex; justify-content: space-between; gap: 18px; align-items: end; padding: 22px; border-bottom: 1px solid var(--line); }
  .remote-tasks h2 { margin: 4px 0 0; font: 800 30px "Iowan Old Style",serif; }
  .remote-tasks-head button, .remote-task-card button { border: 1px solid var(--ink); background: transparent; padding: 9px; font: 900 8px monospace; }
  .remote-task-guide { padding: 18px 22px; border-bottom: 1px solid var(--line); background: #e7e0d2; }
  .remote-task-guide > strong { display: block; margin-bottom: 5px; font: 800 18px "Iowan Old Style",serif; }
  .remote-task-guide > p { max-width: 900px; margin: 0; color: var(--muted); font-size: 10px; line-height: 1.65; }
  .remote-task-summary { margin-top: 8px !important; color: var(--ink) !important; font-weight: 800; }
  .remote-task-guide-grid { display: grid; grid-template-columns: repeat(3,minmax(0,1fr)); gap: 8px; margin-top: 13px; }
  .remote-task-guide-grid div { border-left: 3px solid var(--signal); background: rgba(251,246,236,.72); padding: 10px 12px; }
  .remote-task-guide-grid b { display: block; margin-bottom: 3px; font: 800 12px "Iowan Old Style",serif; }
  .remote-task-guide-grid span { color: var(--muted); font-size: 9px; line-height: 1.5; }
  .remote-task-list { display: grid; grid-template-columns: repeat(3,minmax(0,1fr)); gap: 1px; background: var(--line); }
  .remote-task-list-title { grid-column: 1/-1; margin: 0; background: #ded6c7; padding: 13px 17px; font: 800 18px/1.2 "Iowan Old Style",serif; }
  .remote-task-card { min-width: 0; background: #f2ecdf; padding: 15px; }
  .remote-task-card strong, .remote-task-card span { display: block; overflow-wrap: anywhere; }
  .remote-task-card strong { margin: 7px 0; font: 800 14px "Iowan Old Style",serif; }
  .remote-task-card span { color: var(--muted); font: 8px/1.55 monospace; }
  .remote-task-purpose, .remote-task-next, .remote-task-error { margin: 8px 0; color: var(--muted); font-size: 10px; line-height: 1.55; }
  .remote-task-next { border-left: 3px solid var(--acid); background: rgba(215,228,85,.16); padding: 8px 9px; color: var(--ink); }
  .remote-task-error { border-left: 3px solid var(--signal); background: rgba(211,77,49,.08); padding: 8px 9px; color: var(--ink); }
  .remote-task-actions { display: flex; flex-wrap: wrap; gap: 6px; margin-top: 9px; }
  .remote-task-actions button { background: var(--ink); color: var(--paper); }
  .remote-task-tech { margin-top: 10px; border-top: 1px dashed #aaa293; padding-top: 8px; }
  .remote-task-tech summary { color: var(--muted); cursor: pointer; font: 800 9px monospace; }
  .remote-task-tech span { margin-top: 7px; }
  .remote-task-state { width: fit-content; padding: 5px 7px; background: var(--paper-deep); color: var(--ink) !important; }
  .remote-task-state.completed, .remote-task-state.returned { background: var(--acid); }
  .remote-task-state.failed, .remote-task-state.canceled { background: var(--signal); color: white !important; }
  .remote-lora { margin-top: 14px; border: 1px solid var(--line); background: var(--paper); box-shadow: var(--shadow); }
  .remote-lora-head { display: flex; justify-content: space-between; gap: 18px; align-items: end; padding: 22px; border-bottom: 1px solid var(--line); }
  .remote-lora h2 { margin: 4px 0 0; font: 800 30px "Iowan Old Style",serif; }
  .remote-lora-search { display: flex; gap: 7px; }
  .remote-lora-search input { border: 1px solid var(--line); background: #fbf6ec; padding: 9px; }
  .remote-lora-tools { display: flex; flex-wrap: wrap; justify-content: end; gap: 7px; }
  .remote-lora-search button, .remote-lora-tools > button { border: 1px solid var(--ink); background: var(--ink); color: var(--paper); padding: 9px; font: 900 8px monospace; }
  .remote-lora-tools > button { background: var(--signal); border-color: var(--signal); }
  .remote-lora-search button.secondary { background: transparent; color: var(--ink); }
  .remote-lora-body { display: grid; grid-template-columns: 238px minmax(0,1fr); min-height: 390px; }
  .remote-lora-tree { border-right: 1px solid var(--line); background: #e7e0d2; padding: 16px 12px 22px; }
  .remote-lora-tree-title { display: flex; justify-content: space-between; gap: 8px; align-items: center; margin: 0 4px 12px; color: var(--muted); font: 900 8px monospace; text-transform: uppercase; letter-spacing: .08em; }
  .remote-lora-tree ul { margin: 0; padding: 0; list-style: none; }
  .remote-tree-root + .remote-tree-root { margin-top: 3px; }
  .remote-tree-row { display: grid; grid-template-columns: 22px minmax(0,1fr); gap: 3px; align-items: center; }
  .remote-tree-toggle, .remote-tree-filter { min-width: 0; border: 0; background: transparent; color: var(--ink); cursor: pointer; }
  .remote-tree-toggle { width: 22px; height: 27px; padding: 0; font: 900 10px monospace; }
  .remote-tree-filter { display: flex; justify-content: space-between; gap: 8px; width: 100%; padding: 7px 8px; text-align: left; font: 800 10px/1.2 monospace; }
  .remote-tree-filter:hover, .remote-tree-filter.active { background: var(--ink); color: var(--paper); }
  .remote-tree-filter span { overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
  .remote-tree-filter small { flex: 0 0 auto; color: inherit; font: 700 8px monospace; opacity: .65; }
  .remote-tree-all { grid-column: 1/-1; margin-bottom: 8px; }
  .remote-tree-children { margin: 2px 0 7px 25px !important; padding-left: 7px !important; border-left: 1px solid #aaa293; }
  .remote-tree-children[hidden] { display: none; }
  .remote-tree-children .remote-tree-filter { position: relative; padding: 6px 8px; font-size: 9px; }
  .remote-tree-children .remote-tree-filter::before { content: ''; position: absolute; left: -8px; top: 50%; width: 7px; border-top: 1px solid #aaa293; }
  .remote-lora-results { min-width: 0; }
  .remote-lora-result-head { display: flex; justify-content: space-between; gap: 14px; align-items: center; min-height: 45px; padding: 10px 15px; border-bottom: 1px solid var(--line); background: #f2ecdf; }
  .remote-lora-result-head p { margin: 0; color: var(--muted); font: 800 9px/1.5 monospace; }
  .remote-lora-result-head button { border: 0; border-bottom: 1px solid var(--ink); background: transparent; padding: 4px 0; font: 900 8px monospace; }
  .remote-lora-grid { display: grid; grid-template-columns: repeat(3,minmax(0,1fr)); gap: 1px; background: var(--line); }
  .remote-lora-card { min-width: 0; background: #f2ecdf; padding: 15px; }
  .remote-lora-preview { position: relative; display: block; width: calc(100% + 30px); aspect-ratio: 4/3; margin: -15px -15px 13px; overflow: hidden; border: 0; border-bottom: 1px solid var(--line); background: #d9d1c2; color: var(--muted); cursor: pointer; }
  .remote-lora-preview img { width: 100%; height: 100%; object-fit: cover; transition: transform .24s ease, filter .24s ease; }
  .remote-lora-preview:hover img { transform: scale(1.025); filter: contrast(1.04); }
  .remote-lora-preview-count { position: absolute; right: 9px; bottom: 9px; border: 1px solid rgba(255,255,255,.55); background: rgba(20,19,17,.82); color: white; padding: 5px 7px; font: 900 8px monospace; }
  .remote-lora-placeholder { display: grid; place-items: center; width: calc(100% + 30px); aspect-ratio: 4/3; margin: -15px -15px 13px; border-bottom: 1px solid var(--line); background: repeating-linear-gradient(135deg,#e4ddcf 0 9px,#ddd4c5 9px 10px); color: #8b8275; font: 900 8px monospace; letter-spacing: .08em; text-transform: uppercase; }
  .remote-lora-card h3 { margin: 0 0 8px; overflow-wrap: anywhere; font: 800 16px "Iowan Old Style",serif; }
  .remote-lora-card p { color: var(--muted); font: 8px/1.6 monospace; overflow-wrap: anywhere; }
  .remote-source-link { display: inline-flex; align-items: center; margin-top: 10px; border-bottom: 1px solid currentColor; color: var(--signal); font: 900 8px/1.5 monospace; text-decoration: none; }
  .remote-source-link:hover, .remote-source-link:focus-visible { color: var(--ink); }
  .remote-lora-breadcrumb { display: block; margin-bottom: 7px; color: var(--signal); font: 900 8px/1.4 monospace; text-transform: none; overflow-wrap: anywhere; }
  .remote-model-card { min-height: 170px; }
  .remote-model-type { display: inline-block; margin-bottom: 13px; border: 1px solid var(--ink); background: var(--acid); padding: 5px 7px; font: 900 8px monospace; text-transform: uppercase; }
  .remote-model-size { display: inline-block; margin-left: 5px; color: var(--muted); font: 800 8px monospace; }
  .remote-empty { grid-column: 1/-1; padding: 38px; text-align: center; }
  .remote-empty strong { display: block; font: 800 22px "Iowan Old Style",serif; }
  .remote-empty span { display: block; margin-top: 8px; color: var(--muted); font-size: 10px; }
  .remote-preview-dialog { width: min(1040px,calc(100vw - 32px)); max-height: calc(100vh - 32px); border: 1px solid var(--line); background: var(--paper); color: var(--ink); padding: 0; box-shadow: 14px 14px 0 rgba(20,19,17,.25); }
  .remote-preview-dialog::backdrop { background: rgba(20,19,17,.82); backdrop-filter: blur(3px); }
  .remote-preview-dialog-head { position: sticky; top: 0; z-index: 2; display: flex; justify-content: space-between; gap: 18px; align-items: center; border-bottom: 1px solid var(--line); background: var(--paper); padding: 15px 18px; }
  .remote-preview-dialog-head h3 { margin: 0; font: 800 24px "Iowan Old Style",serif; }
  .remote-preview-dialog-head p { margin: 3px 0 0; color: var(--muted); font: 800 8px monospace; }
  .remote-preview-dialog-head button { border: 1px solid var(--ink); background: var(--ink); color: var(--paper); padding: 9px 12px; font: 900 8px monospace; }
  .remote-preview-gallery { display: grid; grid-template-columns: repeat(2,minmax(0,1fr)); gap: 1px; background: var(--line); }
  .remote-preview-gallery a { min-width: 0; background: #ddd5c7; }
  .remote-preview-gallery img { display: block; width: 100%; height: min(62vh,680px); object-fit: contain; }
  @media (max-width: 1050px) { .remote-lora-grid, .remote-task-list { grid-template-columns: repeat(2,minmax(0,1fr)); } }
  @media (max-width: 820px) { .remote-lora-head { display: block; } .remote-lora-tools { display: grid; grid-template-columns: auto minmax(0,1fr); width: 100%; margin-top: 14px; } .remote-lora-search { display: grid; grid-template-columns: minmax(150px,1fr) auto auto; } }
  @media (max-width: 540px) { .remote-lora-body { grid-template-columns: 1fr; } .remote-lora-tree { border-right: 0; border-bottom: 1px solid var(--line); } }
  @media (max-width: 620px) { .remote-hero, .remote-grid, .remote-lora-grid, .remote-task-list, .remote-task-guide-grid, .remote-preview-gallery { grid-template-columns: 1fr; } .remote-copy { min-height: 0; padding: 30px 22px; border-right: 0; border-bottom: 1px solid var(--line); } .remote-boundary { padding: 24px 22px; } .remote-section-tab { grid-template-columns: 1fr; justify-items: center; gap: 4px; min-height: 74px; padding: 9px 5px; text-align: center; } .remote-section-tab-icon { width: 26px; height: 26px; } .remote-section-tab-copy small { display: none; } .remote-section-tab-copy strong { font-size: 13px; } .remote-section-tab-count { min-width: 0; border: 0; padding: 0; opacity: .65; } .remote-section-tab[aria-selected="true"] .remote-section-tab-count { background: transparent; color: inherit; } .remote-form { grid-template-columns: 1fr; } .remote-form label.wide { grid-column: auto; } .remote-lora-head, .remote-tasks-head { display: block; } .remote-lora-tools, .remote-lora-search { display: grid; grid-template-columns: 1fr; width: 100%; } .remote-lora-tools { justify-content: stretch; margin-top: 12px; } .remote-lora-search, .remote-tasks-head button { margin-top: 5px; } .remote-lora-result-head { align-items: start; } .remote-preview-gallery img { height: auto; max-height: 72vh; } }
</style>
"""

REMOTE_HTML = r"""
<section class="remote-page" id="remotePage" hidden>
  <section class="remote-hero"><div class="remote-copy"><span class="eyebrow">Mac 连接 5060 Ti</span><h1>设备<br>连接</h1><p>在这里查看 Windows 的运行状态、接收 ComfyUI 出图结果，以及更新 LoRA 和底模清单。数据集整理仍在 Mac 完成；筛标、正则和训练仍由你在 Windows 的 AnimaLoraStudio 中操作。</p></div><aside class="remote-boundary"><span class="section-label">登录信息放在哪里</span><strong>密码由 Mac 钥匙串保存</strong><p>先用 Finder 连接 Windows 共享文件夹，并选择记住密码。这里仅填写 Windows 地址和 Mac 上已经连接好的文件夹位置，不会保存账号密码。</p></aside></section>
  <nav class="remote-section-tabs" id="remoteSectionTabs" role="tablist" aria-label="设备连接子页面">
    <button class="remote-section-tab" id="remoteTasksTab" type="button" role="tab" aria-selected="true" aria-controls="remoteTasksPanel" data-remote-view="tasks"><span class="remote-section-tab-icon" aria-hidden="true">●</span><span class="remote-section-tab-copy"><small>01 / 任务</small><strong>任务状态</strong></span><span class="remote-section-tab-count" id="remoteTasksCount">—</span></button>
    <button class="remote-section-tab" id="remoteLoraTab" type="button" role="tab" aria-selected="false" aria-controls="remoteLoraPanel" tabindex="-1" data-remote-view="loras"><span class="remote-section-tab-icon" aria-hidden="true">L</span><span class="remote-section-tab-copy"><small>02 / 模型库</small><strong>LoRA</strong></span><span class="remote-section-tab-count" id="remoteLoraCount">—</span></button>
    <button class="remote-section-tab" id="remoteModelTab" type="button" role="tab" aria-selected="false" aria-controls="remoteModelPanel" tabindex="-1" data-remote-view="models"><span class="remote-section-tab-icon" aria-hidden="true">M</span><span class="remote-section-tab-copy"><small>03 / 模型库</small><strong>底模</strong></span><span class="remote-section-tab-count" id="remoteModelCount">—</span></button>
  </nav>
  <section class="remote-section-panel" id="remoteTasksPanel" role="tabpanel" aria-labelledby="remoteTasksTab" data-remote-panel="tasks">
    <div class="remote-grid" id="remoteNodeGrid"></div>
    <section class="remote-tasks"><div class="remote-tasks-head"><div><span class="section-label">Mac 发给 Windows 的工作</span><h2>任务状态</h2><p>先看“需要处理”：正在执行、等待接收或等待你导入的任务都会放在那里。完成、失败和取消的任务收在“历史记录”中。</p><p class="remote-task-summary" id="remoteTaskSummary">正在统计任务记录……</p></div><button id="remoteTaskRefresh" type="button">刷新任务状态</button></div><div class="remote-task-guide"><strong>这里会出现哪些任务？</strong><p>这里只记录 Mac 与 5060 Ti 之间的出图和模型清单更新，不是 LoRA 训练列表。通常只需看卡片里的“现在”说明；任务编号仅用于排查问题。</p><div class="remote-task-guide-grid"><div><b>ComfyUI 出图</b><span>把创作台的绘图请求交给 5060 Ti，完成后把图片接回 Mac。</span></div><div><b>更新 LoRA 清单</b><span>读取 Windows 中的 LoRA 名称、分类、预览和来源，不复制模型文件。</span></div><div><b>更新底模清单</b><span>读取 Windows 中的底模、组件和示例图，不复制模型文件。</span></div></div></div><div class="remote-task-list" id="remoteTaskList"></div></section>
  </section>
  <section class="remote-section-panel" id="remoteLoraPanel" role="tabpanel" aria-labelledby="remoteLoraTab" data-remote-panel="loras" hidden>
    <section class="remote-lora"><div class="remote-lora-head"><div><span class="section-label">来自 LoRA Manager 的只读清单</span><h2>查看 Windows 上的 LoRA</h2><p id="remoteLoraStatus">正在读取 Windows 上一次发来的清单……</p></div><div class="remote-lora-tools"><button id="remoteLoraSync" type="button">从 Windows 更新清单</button><form class="remote-lora-search" id="remoteLoraSearch"><input id="remoteLoraQuery" placeholder="名称 / 路径 / 触发词 / 底模 / 标签"><button type="submit">查找 LoRA</button><button class="secondary" id="remoteLoraClear" type="button">清除筛选</button></form></div></div><div class="remote-lora-body"><nav class="remote-lora-tree" aria-label="LoRA 目录树"><div class="remote-lora-tree-title"><span>Windows 文件夹</span><span>LoRA 数量</span></div><ul id="remoteLoraTree"></ul></nav><div class="remote-lora-results"><div class="remote-lora-result-head"><p id="remoteLoraResultStatus">正在整理目录……</p><button id="remoteLoraResetPath" type="button" hidden>返回全部目录</button></div><div class="remote-lora-grid" id="remoteLoraGrid"></div></div></div></section>
  </section>
  <section class="remote-section-panel" id="remoteModelPanel" role="tabpanel" aria-labelledby="remoteModelTab" data-remote-panel="models" hidden>
    <section class="remote-lora remote-model"><div class="remote-lora-head"><div><span class="section-label">只读取名称、分类、来源和示例图</span><h2>查看 Windows 上的模型</h2><p id="remoteModelStatus">正在读取 Windows 上一次发来的模型清单……</p></div><div class="remote-lora-tools"><button id="remoteModelSync" type="button">从 Windows 更新清单</button><form class="remote-lora-search" id="remoteModelSearch"><input id="remoteModelQuery" placeholder="名称 / 路径 / 类型 / 模型系列"><button type="submit">查找模型</button><button class="secondary" id="remoteModelClear" type="button">清除筛选</button></form></div></div><div class="remote-lora-body"><nav class="remote-lora-tree" aria-label="模型类型与目录树"><div class="remote-lora-tree-title"><span>类型 / 文件夹</span><span>数量</span></div><ul id="remoteModelTree"></ul></nav><div class="remote-lora-results"><div class="remote-lora-result-head"><p id="remoteModelResultStatus">正在整理模型目录……</p><button id="remoteModelResetPath" type="button" hidden>返回全部模型</button></div><div class="remote-lora-grid" id="remoteModelGrid"></div></div></div></section>
  </section>
</section>
<dialog class="remote-preview-dialog" id="remotePreviewDialog"><div class="remote-preview-dialog-head"><div><h3 id="remotePreviewTitle">LoRA 视觉参照</h3><p id="remotePreviewMeta"></p></div><button id="remotePreviewClose" type="button">关闭</button></div><div class="remote-preview-gallery" id="remotePreviewGallery"></div></dialog>
"""

REMOTE_SCRIPT = r"""
<script>
(() => {
  const defaults=[{node_id:'compute-5060ti',label:'5060 Ti · 绘图与模型清单',role:'compute_5060ti',capabilities:['comfyui_generate','workflow_test','result_metadata','wd14_batch','embedding_batch','vlm_caption_batch','lora_catalog_snapshot','model_catalog_snapshot','lora_train','checkpoint_test']}];
  const state={nodes:[],catalog:[],loras:[],modelsCatalog:[],models:[],tasks:[],remoteView:'tasks',loraQuery:'',loraRoot:'',loraCategory:'',modelQuery:'',modelType:'',modelFolder:'',collapsedLoraRoots:new Set(),collapsedModelTypes:new Set(),loraTreeReady:false,modelTreeReady:false};
  const remoteStateLabels={ready:'共享目录已就绪',mount_missing:'共享目录未挂载',mount_ready_bridge_unprepared:'需要创建任务文件夹',bridge_read_only:'共享目录不可写',not_configured:'尚未配置'};
  async function api(url,options={}) { const response=await fetch(url,options); const payload=await response.json().catch(()=>({})); if(!response.ok) throw new Error(payload.detail||`请求失败: ${response.status}`); return payload; }
  function setRemoteTabCount(view,count) { const target=$(`[data-remote-view="${view}"] .remote-section-tab-count`); if(target) target.textContent=String(count); }
  function setRemoteView(view,{focus=false}={}) { if(!['tasks','loras','models'].includes(view)) return; state.remoteView=view; document.querySelectorAll('[data-remote-view]').forEach(tab=>{ const active=tab.dataset.remoteView===view; tab.setAttribute('aria-selected',String(active)); tab.tabIndex=active?0:-1; if(active&&focus) tab.focus(); }); document.querySelectorAll('[data-remote-panel]').forEach(panel=>{ panel.hidden=panel.dataset.remotePanel!==view; }); }
  function combinedNodes() { return defaults.map(fallback=>({...fallback,...(state.nodes.find(item=>item.node_id===fallback.node_id)||{})})); }
  function nodeCard(node) { const mountPlaceholder='/Volumes/PromptHub-5060Ti',roleLabel=node.role==='compute_5060ti'?'5060 Ti 远程设备':node.role; return `<article class="remote-card" data-remote-node="${escapeHtml(node.node_id)}"><div class="remote-card-head"><div><span class="section-label">${escapeHtml(roleLabel)}</span><h2>${escapeHtml(node.label)}</h2></div><span class="remote-state" data-remote-state>尚未检查</span></div><div class="remote-form"><label>主机名或局域网 IP<input data-node-field="host" value="${escapeHtml(node.host||'')}" placeholder="等待填写"></label><label>设备显示名<input data-node-field="label" value="${escapeHtml(node.label)}"></label><label class="wide">Mac 已连接的 Windows 文件夹<input data-node-field="smb_mount" value="${escapeHtml(node.smb_mount||'')}" placeholder="${mountPlaceholder}"></label><label class="remote-check wide"><input data-node-field="enabled" type="checkbox" ${node.enabled?'checked':''}> 启用这台设备</label></div><div class="remote-actions"><button class="primary" data-remote-action="save">保存设备信息</button><button data-remote-action="diagnose">检查是否连接成功</button><button data-remote-action="prepare">创建任务文件夹</button></div><div class="remote-message" data-remote-message>尚未配置。先在 Finder 连接 5060 Ti 的共享文件夹，再填写这里。</div></article>`; }
  function renderNodes() { $('#remoteNodeGrid').innerHTML=combinedNodes().map(nodeCard).join(''); }
  const taskTypeInfo={comfyui_generate:{label:'ComfyUI 出图',purpose:'把创作台中的绘图请求交给 5060 Ti，生成结果可以接回 Mac。'},lora_catalog_snapshot:{label:'更新 LoRA 清单',purpose:'读取 Windows 中的 LoRA 名称、分类、预览图和 Civitai 来源，不复制模型文件。'},model_catalog_snapshot:{label:'更新底模清单',purpose:'读取 Windows 中的底模与组件清单、示例图和 Civitai 来源，不复制模型文件。'},embedding_batch:{label:'建立相似图索引（可选）',purpose:'批量计算以图找图所需的视觉特征，不是打标或训练。'},vlm_caption_batch:{label:'生成 Krea 2 描述草稿（可选）',purpose:'批量看图并生成 Krea 2 英文描述草稿，仍需在 Mac 人工确认。'},wd14_batch:{label:'WD14 批量打标',purpose:'为图片生成 Anima 标签草稿，不直接覆盖人工说明文字。'},lora_train:{label:'LoRA 训练任务（未接入）',purpose:'预留的旧任务类型；当前训练仍由你在 Windows 的 AnimaLoraStudio 中操作。'},checkpoint_test:{label:'模型测试出图',purpose:'使用指定模型生成测试图。'},workflow_test:{label:'工作流测试',purpose:'检查 ComfyUI 工作流能否正常运行。'},result_metadata:{label:'读取图片参数',purpose:'读取生成图片中已有的 ComfyUI 参数。'}};
  function taskNextStep(item) { if(item.status==='recorded') return 'Mac 已保存这项任务，正在准备放入共享文件夹。'; if(item.status==='queued') return '等待 Windows 接收。请保持 Windows 和 Worker 开启。'; if(item.status==='running') return 'Windows 正在处理，现在不需要在 Mac 操作。'; if(item.status==='returned') return 'Windows 已把结果送回 Mac。请点击卡片下方的接收按钮；如果以前已经接收，可以忽略这条旧记录。'; if(item.status==='completed') return '结果已经接收并保存，不需要继续操作。'; if(item.status==='failed') return '这项任务没有完成。查看失败原因，需要时点击“重新投递”。'; if(item.status==='canceled') return '这项任务已取消；如果还需要，可以点击“重新投递”。'; return '这是旧版本任务状态；展开技术信息可查看原始记录。'; }
  function friendlyTaskError(error) { const raw=String(error||''); if(raw.includes('value_bigger_than_max')&&raw.toLowerCase().includes('seed')) return '随机种子超出 ComfyUI 允许范围。可以点“重新投递”生成新任务。'; if(raw.includes('generation_package 必须出现在已校验的 manifest 中')) return '旧任务包缺少完整性登记，Windows 没有执行。这个旧记录可以忽略，或点击“重新投递”。'; return 'Windows 没能完成这项任务。展开“查看技术信息”可查看原始错误。'; }
  function taskCard(item) { const labels={recorded:'等待发送到 Windows',queued:'等待 Windows 领取',running:'Windows 正在执行',returned:'等待你接收结果',completed:'已完成',failed:'执行失败',canceled:'已取消'}, info=taskTypeInfo[item.task_type]||{label:'其他系统任务',purpose:'这是系统保留的旧任务类型；通常不需要手动处理。'},retry=['failed','canceled'].includes(item.status)||['failed','canceled'].includes(item.result_status),actions=[]; if(retry) actions.push(`<button data-task-action="retry" data-task-id="${escapeHtml(item.task_id)}" data-task-node="${escapeHtml(item.node_id)}">重新投递</button>`); if(['queued','running'].includes(item.status)) actions.push(`<button data-task-action="cancel" data-task-id="${escapeHtml(item.task_id)}" data-task-node="${escapeHtml(item.node_id)}">取消任务</button>`); if(item.status==='returned') actions.push(`<button data-task-action="integrity" data-task-id="${escapeHtml(item.task_id)}" data-task-node="${escapeHtml(item.node_id)}">检查文件完整性</button>`); if(item.status==='returned'&&item.result_status==='completed'&&item.task_type==='comfyui_generate') actions.push(`<button data-task-action="import" data-task-id="${escapeHtml(item.task_id)}" data-task-node="${escapeHtml(item.node_id)}">接收并导入图片</button>`); if(item.status==='returned'&&item.result_status==='completed'&&item.task_type==='lora_catalog_snapshot') actions.push(`<button data-task-action="import-loras" data-task-id="${escapeHtml(item.task_id)}" data-task-node="${escapeHtml(item.node_id)}">接收 LoRA 清单</button>`); if(item.status==='returned'&&item.result_status==='completed'&&item.task_type==='model_catalog_snapshot') actions.push(`<button data-task-action="import-models" data-task-id="${escapeHtml(item.task_id)}" data-task-node="${escapeHtml(item.node_id)}">接收底模清单</button>`); const error=item.error?`<p class="remote-task-error"><b>失败原因：</b>${escapeHtml(friendlyTaskError(item.error))}</p>`:''; return `<article class="remote-task-card" data-task-type="${escapeHtml(item.task_type||'unknown')}"><span class="remote-task-state ${escapeHtml(item.status)}">${escapeHtml(labels[item.status]||item.status)}</span><strong>${escapeHtml(info.label)}</strong><p class="remote-task-purpose">${escapeHtml(info.purpose)}</p><p class="remote-task-next"><b>现在：</b>${escapeHtml(taskNextStep(item))}</p>${error}<div class="remote-task-actions">${actions.join('')}</div><details class="remote-task-tech"><summary>查看技术信息</summary><span>任务编号：${escapeHtml(item.task_id)}<br>第 ${item.attempt||1} 次投递<br>执行设备：${escapeHtml(item.node_label)}${item.worker_id?`<br>执行程序：${escapeHtml(item.worker_id)}`:''}<br>底层类型：${escapeHtml(item.task_type||'unknown')}${item.error?`<br>原始错误：${escapeHtml(item.error)}`:''}</span></details></article>`; }
  function renderTasks() { const current=state.tasks.filter(item=>['recorded','queued','running','returned'].includes(item.status)),history=state.tasks.filter(item=>!['recorded','queued','running','returned'].includes(item.status)); setRemoteTabCount('tasks',`${current.length} 待处理`); $('#remoteTaskSummary').textContent=current.length?`${current.length} 条需要处理 · ${history.length} 条历史记录`:`目前没有需要处理的任务 · ${history.length} 条历史记录`; const currentHtml=current.length?current.map(taskCard).join(''):'<div class="remote-empty"><strong>现在没有需要处理的任务</strong><span>从创作台发送出图，或从 LoRA、底模页面更新清单后，新任务会显示在这里。</span></div>'; const historyHtml=history.length?history.map(taskCard).join(''):'<div class="remote-empty"><strong>还没有历史记录</strong><span>完成、失败或取消的任务会收在这里。</span></div>'; $('#remoteTaskList').innerHTML=`<h3 class="remote-task-list-title">需要处理</h3>${currentHtml}<h3 class="remote-task-list-title">历史记录</h3>${historyHtml}`; }
  function loraLocation(item) { const parts=String(item.relative_path||'').split('/').filter(Boolean); return {root:parts.length>1?parts[0]:'未分类',category:parts.length>2?parts[1]:'未分类'}; }
  function loraKey(value) { return String(value||'').trim().toLocaleLowerCase(); }
  function loraTreeData() { const roots=new Map(); state.catalog.forEach(item=>{ const location=loraLocation(item),rootKey=loraKey(location.root),categoryKey=loraKey(location.category); if(!roots.has(rootKey)) roots.set(rootKey,{key:rootKey,label:location.root,count:0,categories:new Map()}); const root=roots.get(rootKey); root.count+=1; if(!root.categories.has(categoryKey)) root.categories.set(categoryKey,{key:categoryKey,label:location.category,count:0}); root.categories.get(categoryKey).count+=1; }); return [...roots.values()].sort((a,b)=>a.label.localeCompare(b.label,'zh-CN',{numeric:true,sensitivity:'base'})).map(root=>({...root,categories:[...root.categories.values()].sort((a,b)=>a.label.localeCompare(b.label,'zh-CN',{numeric:true,sensitivity:'base'}))})); }
  function renderLoraTree() { const allActive=!state.loraRoot,tree=loraTreeData(); $('#remoteLoraTree').innerHTML=`<li class="remote-tree-row"><button class="remote-tree-filter remote-tree-all ${allActive?'active':''}" type="button" data-lora-root="" data-lora-category=""><span>全部 LoRA</span><small>${state.catalog.length}</small></button></li>`+tree.map(root=>{ const collapsed=state.collapsedLoraRoots.has(root.key),rootActive=state.loraRoot===root.key&&!state.loraCategory; return `<li class="remote-tree-root"><div class="remote-tree-row"><button class="remote-tree-toggle" type="button" data-lora-tree-toggle="${escapeHtml(root.key)}" aria-label="${collapsed?'展开':'收起'} ${escapeHtml(root.label)}" aria-expanded="${!collapsed}">${collapsed?'＋':'−'}</button><button class="remote-tree-filter ${rootActive?'active':''}" type="button" data-lora-root="${escapeHtml(root.key)}" data-lora-category=""><span>${escapeHtml(root.label)}</span><small>${root.count}</small></button></div><ul class="remote-tree-children" ${collapsed?'hidden':''}>${root.categories.map(category=>`<li><button class="remote-tree-filter ${state.loraRoot===root.key&&state.loraCategory===category.key?'active':''}" type="button" data-lora-root="${escapeHtml(root.key)}" data-lora-category="${escapeHtml(category.key)}"><span>${escapeHtml(category.label)}</span><small>${category.count}</small></button></li>`).join('')}</ul></li>`; }).join(''); }
  function civitaiLink(item) { return item.source_url?`<a class="remote-source-link" href="${escapeHtml(item.source_url)}" target="_blank" rel="noreferrer">查看 Civitai / 提示词 ↗</a>`:''; }
  function loraCard(item) { const tags=(item.tags||[]).slice(0,12).map(tag=>window.displayCanonicalTag?.(tag)||tag),location=loraLocation(item),previews=item.preview_urls||[],visual=previews.length?`<button class="remote-lora-preview" type="button" data-lora-preview="${escapeHtml(item.lora_id)}" aria-label="查看 ${escapeHtml(item.name)} 的 ${previews.length} 张视觉参照"><img src="${escapeHtml(previews[0])}" alt="${escapeHtml(item.name)} 预览图" loading="lazy"><span class="remote-lora-preview-count">${previews.length} 张</span></button>`:'<div class="remote-lora-placeholder">暂无本地预览图</div>'; return `<article class="remote-lora-card">${visual}<span class="remote-lora-breadcrumb">${escapeHtml(location.root)} / ${escapeHtml(location.category)}</span><span class="section-label">${escapeHtml(item.model_family||'未识别')}</span><h3>${escapeHtml(item.name)}</h3><p>${escapeHtml(item.relative_path)}<br>适用底模：${escapeHtml(item.base_model||'未标注')}<br>触发词：${escapeHtml((item.trigger_words||[]).join(', ')||'未标注')}<br>标签：${escapeHtml(tags.join(', ')||'未标注')}</p>${civitaiLink(item)}</article>`; }
  function filterLoras() { const needle=loraKey(state.loraQuery); state.loras=state.catalog.filter(item=>{ const location=loraLocation(item); if(state.loraRoot&&loraKey(location.root)!==state.loraRoot) return false; if(state.loraCategory&&loraKey(location.category)!==state.loraCategory) return false; if(!needle) return true; const searchable=[item.name,item.relative_path,item.base_model,item.model_family,item.source_url,item.metadata?.civitai_model_id,item.metadata?.civitai_version_id,...(item.trigger_words||[]),...(item.tags||[])].join(' ').toLocaleLowerCase(); return searchable.includes(needle); }); }
  function renderLoras() { filterLoras(); renderLoraTree(); const tree=loraTreeData(),root=tree.find(item=>item.key===state.loraRoot),category=root?.categories.find(item=>item.key===state.loraCategory),path=[root?.label,category?.label].filter(Boolean).join(' / ')||'全部目录',query=state.loraQuery?` · 搜索“${state.loraQuery}”`:''; $('#remoteLoraResultStatus').textContent=`${path}${query} · 当前 ${state.loras.length} / ${state.catalog.length} 个`; $('#remoteLoraResetPath').hidden=!state.loraRoot&&!state.loraQuery; $('#remoteLoraGrid').innerHTML=state.loras.length?state.loras.map(loraCard).join(''):state.catalog.length?'<div class="remote-empty"><strong>当前筛选没有结果</strong><span>可以切换左侧目录，或清除搜索条件。</span></div>':'<div class="remote-empty"><strong>还没有收到 Windows 的 LoRA 清单</strong><span>Windows 开机并运行 Worker 后，点击“从 Windows 更新清单”；Mac 只保存清单，不复制模型文件。</span></div>'; }
  async function loadNodes() { state.nodes=await api('/api/remote-nodes'); renderNodes(); }
  async function loadTasks() { const groups=await Promise.all(state.nodes.map(async node=>{ try { const tasks=await api(`/api/remote-nodes/${encodeURIComponent(node.node_id)}/tasks?limit=100`); return tasks.map(item=>({...item,node_id:node.node_id,node_label:node.label})); } catch(error) { return []; } })); state.tasks=groups.flat().sort((a,b)=>String(b.updated_at||b.created_at).localeCompare(String(a.updated_at||a.created_at))); renderTasks(); }
  async function loadLoras(query=state.loraQuery) { const status=await api('/api/windows-loras/status'); $('#remoteLoraStatus').textContent=status.available?`${status.count} 个 LoRA · ${status.with_preview_count||0} 个有示例图 · ${status.with_source_count||0} 个可以返回 Civitai · 共 ${status.preview_count||0} 张预览 · 不复制模型文件`:'还没有收到清单。保持 ComfyUI 与 Worker 运行，然后点击“从 Windows 更新清单”。'; const result=await api('/api/windows-loras?limit=500'); state.catalog=result.results||[]; setRemoteTabCount('loras',state.catalog.length); state.loraQuery=query; if(!state.loraTreeReady) { loraTreeData().forEach(root=>{ if(root.key!=='anima') state.collapsedLoraRoots.add(root.key); }); state.loraTreeReady=true; } await window.ensureTagLabels?.(state.catalog.flatMap(item=>item.tags||[])); renderLoras(); }
  const modelTypeLabels={checkpoint:'Checkpoint 底模',diffusion_model:'扩散模型 / UNet',vae:'VAE',text_encoder:'文本编码器',upscaler:'放大模型',controlnet:'ControlNet'};
  function modelKey(value) { return String(value||'').trim().toLocaleLowerCase(); }
  function modelLocation(item) { const parts=String(item.relative_path||'').split('/').filter(Boolean); return {type:String(item.asset_type||'unknown'),folder:parts.length>1?parts[0]:'根目录'}; }
  function modelTreeData() { const types=new Map(); state.modelsCatalog.forEach(item=>{ const location=modelLocation(item),typeKey=modelKey(location.type),folderKey=modelKey(location.folder); if(!types.has(typeKey)) types.set(typeKey,{key:typeKey,label:modelTypeLabels[location.type]||location.type,count:0,folders:new Map()}); const type=types.get(typeKey); type.count+=1; if(!type.folders.has(folderKey)) type.folders.set(folderKey,{key:folderKey,label:location.folder,count:0}); type.folders.get(folderKey).count+=1; }); return [...types.values()].sort((a,b)=>a.label.localeCompare(b.label,'zh-CN',{numeric:true,sensitivity:'base'})).map(type=>({...type,folders:[...type.folders.values()].sort((a,b)=>a.label.localeCompare(b.label,'zh-CN',{numeric:true,sensitivity:'base'}))})); }
  function renderModelTree() { const allActive=!state.modelType,tree=modelTreeData(); $('#remoteModelTree').innerHTML=`<li class="remote-tree-row"><button class="remote-tree-filter remote-tree-all ${allActive?'active':''}" type="button" data-model-type="" data-model-folder=""><span>全部模型</span><small>${state.modelsCatalog.length}</small></button></li>`+tree.map(type=>{ const collapsed=state.collapsedModelTypes.has(type.key),typeActive=state.modelType===type.key&&!state.modelFolder; return `<li class="remote-tree-root"><div class="remote-tree-row"><button class="remote-tree-toggle" type="button" data-model-tree-toggle="${escapeHtml(type.key)}" aria-label="${collapsed?'展开':'收起'} ${escapeHtml(type.label)}" aria-expanded="${!collapsed}">${collapsed?'＋':'−'}</button><button class="remote-tree-filter ${typeActive?'active':''}" type="button" data-model-type="${escapeHtml(type.key)}" data-model-folder=""><span>${escapeHtml(type.label)}</span><small>${type.count}</small></button></div><ul class="remote-tree-children" ${collapsed?'hidden':''}>${type.folders.map(folder=>`<li><button class="remote-tree-filter ${state.modelType===type.key&&state.modelFolder===folder.key?'active':''}" type="button" data-model-type="${escapeHtml(type.key)}" data-model-folder="${escapeHtml(folder.key)}"><span>${escapeHtml(folder.label)}</span><small>${folder.count}</small></button></li>`).join('')}</ul></li>`; }).join(''); }
  function formatModelSize(value) { const bytes=Number(value)||0; if(bytes>=1073741824) return `${(bytes/1073741824).toFixed(1)} GiB`; if(bytes>=1048576) return `${(bytes/1048576).toFixed(1)} MiB`; if(bytes>=1024) return `${(bytes/1024).toFixed(1)} KiB`; return `${bytes} B`; }
  function modelCard(item) { const location=modelLocation(item),typeLabel=modelTypeLabels[item.asset_type]||item.asset_type||'未分类模型',previews=item.preview_urls||[],visual=previews.length?`<button class="remote-lora-preview" type="button" data-model-preview="${escapeHtml(item.asset_id)}" aria-label="查看 ${escapeHtml(item.name)} 的 ${previews.length} 张底模示例图"><img src="${escapeHtml(previews[0])}" alt="${escapeHtml(item.name)} 底模示例图" loading="lazy"><span class="remote-lora-preview-count">${previews.length} 张</span></button>`:'<div class="remote-lora-placeholder">暂无底模示例图</div>'; return `<article class="remote-lora-card remote-model-card">${visual}<span class="remote-model-type">${escapeHtml(typeLabel)}</span><span class="remote-model-size">${escapeHtml(formatModelSize(item.size_bytes))}</span><span class="remote-lora-breadcrumb">${escapeHtml(location.folder)} / ${escapeHtml(item.root_id||'未记录位置')}</span><span class="section-label">${escapeHtml(item.model_family||'未标注模型族')}</span><h3>${escapeHtml(item.name)}</h3><p>${escapeHtml(item.relative_path)}<br>修改时间：${escapeHtml(item.modified_at||'未知')}</p>${civitaiLink(item)}</article>`; }
  function filterModels() { const needle=modelKey(state.modelQuery); state.models=state.modelsCatalog.filter(item=>{ const location=modelLocation(item); if(state.modelType&&modelKey(location.type)!==state.modelType) return false; if(state.modelFolder&&modelKey(location.folder)!==state.modelFolder) return false; if(!needle) return true; return [item.name,item.relative_path,item.root_id,item.asset_type,item.model_family,item.source_url,item.metadata?.civitai_model_id,item.metadata?.civitai_version_id].join(' ').toLocaleLowerCase().includes(needle); }); }
  function renderModels() { filterModels(); renderModelTree(); const tree=modelTreeData(),type=tree.find(item=>item.key===state.modelType),folder=type?.folders.find(item=>item.key===state.modelFolder),path=[type?.label,folder?.label].filter(Boolean).join(' / ')||'全部模型',query=state.modelQuery?` · 搜索“${state.modelQuery}”`:''; $('#remoteModelResultStatus').textContent=`${path}${query} · 当前 ${state.models.length} / ${state.modelsCatalog.length} 个`; $('#remoteModelResetPath').hidden=!state.modelType&&!state.modelQuery; $('#remoteModelGrid').innerHTML=state.models.length?state.models.map(modelCard).join(''):state.modelsCatalog.length?'<div class="remote-empty"><strong>当前筛选没有模型</strong><span>可以切换左侧类型或文件夹，也可以清除搜索条件。</span></div>':'<div class="remote-empty"><strong>还没有收到 Windows 的模型清单</strong><span>Windows 开机并运行 Worker 后，点击“从 Windows 更新清单”；Mac 只保存名称、目录、大小和时间，不复制模型文件。</span></div>'; }
  async function loadModels(query=state.modelQuery) { const status=await api('/api/windows-models/status'); const counts=Object.entries(status.type_counts||{}).map(([key,value])=>`${modelTypeLabels[key]||key} ${value}`).join(' · '); $('#remoteModelStatus').textContent=status.available?`${status.count} 个模型 · ${status.with_preview_count||0} 个有示例图 · ${status.with_source_count||0} 个可以返回 Civitai · 共 ${status.preview_count||0} 张预览 · ${counts||'未分类'} · 不复制模型文件`:'还没有收到清单。保持 ComfyUI 与 Worker 运行，然后点击“从 Windows 更新清单”。'; const result=await api('/api/windows-models?limit=2000'); state.modelsCatalog=result.results||[]; setRemoteTabCount('models',state.modelsCatalog.length); state.modelQuery=query; if(!state.modelTreeReady) { modelTreeData().forEach(type=>state.collapsedModelTypes.add(type.key)); state.modelTreeReady=true; } renderModels(); }
  function openAssetPreviews(item,label) { const dialog=$('#remotePreviewDialog'); if(!item||(item.preview_urls||[]).length===0) return; $('#remotePreviewTitle').textContent=item.name; $('#remotePreviewMeta').textContent=`${item.relative_path} · ${(item.preview_urls||[]).length} 张本机缓存${label}`; $('#remotePreviewGallery').innerHTML=item.preview_urls.map((url,index)=>`<a href="${escapeHtml(url)}" target="_blank" rel="noreferrer" title="在新窗口打开原图"><img src="${escapeHtml(url)}" alt="${escapeHtml(item.name)} ${escapeHtml(label)} ${index+1}" loading="lazy"></a>`).join(''); dialog.showModal(); }
  function openLoraPreviews(loraId) { openAssetPreviews(state.catalog.find(value=>value.lora_id===loraId),'LoRA 视觉参照'); }
  function openModelPreviews(assetId) { openAssetPreviews(state.modelsCatalog.find(value=>value.asset_id===assetId),'底模示例图'); }
  function payload(card,node) { return {label:card.querySelector('[data-node-field="label"]').value.trim(),role:node.role,host:card.querySelector('[data-node-field="host"]').value.trim(),smb_mount:card.querySelector('[data-node-field="smb_mount"]').value.trim(),enabled:card.querySelector('[data-node-field="enabled"]').checked,capabilities:node.capabilities||[],notes:''}; }
  async function act(card,action) { const nodeId=card.dataset.remoteNode,node=combinedNodes().find(item=>item.node_id===nodeId),message=card.querySelector('[data-remote-message]'),badge=card.querySelector('[data-remote-state]'); if(action==='save') { const saved=await api(`/api/remote-nodes/${encodeURIComponent(nodeId)}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload(card,node))}); state.nodes=state.nodes.filter(item=>item.node_id!==nodeId).concat(saved); message.textContent='设备位置已保存；未保存任何用户名或密码。'; return; } if(action==='prepare'&&!confirm('确认在已挂载的 SMB 目录中建立 prompt-hub/outbox、inbox、processing、completed、failed 五个文件夹？')) return; const endpoint=action==='prepare'?`/api/remote-nodes/${encodeURIComponent(nodeId)}/prepare`:`/api/remote-nodes/${encodeURIComponent(nodeId)}/diagnostics`, result=await api(endpoint,action==='prepare'?{method:'POST'}:{}); badge.textContent=result.worker_ready?'Windows 已就绪':remoteStateLabels[result.state]||'状态待确认'; badge.className=`remote-state ${result.state}`; message.textContent=result.worker_ready?`Windows Worker 与本机 ComfyUI 已通过自检。Python / ${result.worker_status?.python||'未知'} · 设备 / ${result.worker_status?.hostname||'未知'}`:result.state==='ready'?'共享目录已就绪；等待 Windows 运行“1-先自检.bat”。':result.state==='mount_missing'?'Mac 还看不到这个 SMB 目录。请先在 Finder 连接服务器并挂载。':result.state==='mount_ready_bridge_unprepared'?'SMB 已挂载；可以建立五个交付目录。':result.state==='bridge_read_only'?'共享目录当前不可写，请检查 Windows 共享权限。':result.state==='not_configured'?'尚未填写主机地址和 SMB 挂载路径。':'当前状态需要进一步检查。'; }
  async function ensure() { await loadNodes(); await Promise.all([loadLoras(),loadModels(),loadTasks()]); }
  $('#remoteSectionTabs').addEventListener('click',event=>{ const tab=event.target.closest('[data-remote-view]'); if(tab) setRemoteView(tab.dataset.remoteView); });
  $('#remoteSectionTabs').addEventListener('keydown',event=>{ if(!['ArrowLeft','ArrowRight','Home','End'].includes(event.key)) return; const tabs=[...document.querySelectorAll('[data-remote-view]')],current=tabs.indexOf(event.target.closest('[data-remote-view]')); if(current<0) return; event.preventDefault(); const next=event.key==='Home'?0:event.key==='End'?tabs.length-1:(current+(event.key==='ArrowRight'?1:-1)+tabs.length)%tabs.length; setRemoteView(tabs[next].dataset.remoteView,{focus:true}); });
  $('#remoteNodeGrid').addEventListener('click',event=>{ const button=event.target.closest('[data-remote-action]'); if(!button) return; const card=button.closest('[data-remote-node]'); button.disabled=true; act(card,button.dataset.remoteAction).catch(error=>card.querySelector('[data-remote-message]').textContent=error.message).finally(()=>button.disabled=false); });
  $('#remoteLoraSearch').addEventListener('submit',event=>{ event.preventDefault(); state.loraQuery=$('#remoteLoraQuery').value.trim(); renderLoras(); });
  $('#remoteLoraTree').addEventListener('click',event=>{ const toggle=event.target.closest('[data-lora-tree-toggle]'); if(toggle) { const key=toggle.dataset.loraTreeToggle; if(state.collapsedLoraRoots.has(key)) state.collapsedLoraRoots.delete(key); else state.collapsedLoraRoots.add(key); renderLoraTree(); return; } const filter=event.target.closest('[data-lora-root]'); if(!filter) return; state.loraRoot=filter.dataset.loraRoot||''; state.loraCategory=filter.dataset.loraCategory||''; if(state.loraRoot) state.collapsedLoraRoots.delete(state.loraRoot); renderLoras(); });
  $('#remoteLoraGrid').addEventListener('click',event=>{ const button=event.target.closest('[data-lora-preview]'); if(button) openLoraPreviews(button.dataset.loraPreview); });
  $('#remoteModelGrid').addEventListener('click',event=>{ const button=event.target.closest('[data-model-preview]'); if(button) openModelPreviews(button.dataset.modelPreview); });
  $('#remotePreviewClose').addEventListener('click',()=>$('#remotePreviewDialog').close());
  $('#remotePreviewDialog').addEventListener('click',event=>{ if(event.target===$('#remotePreviewDialog')) $('#remotePreviewDialog').close(); });
  function clearLoraFilters() { state.loraQuery=''; state.loraRoot=''; state.loraCategory=''; $('#remoteLoraQuery').value=''; renderLoras(); }
  $('#remoteLoraClear').addEventListener('click',clearLoraFilters);
  $('#remoteLoraResetPath').addEventListener('click',clearLoraFilters);
  $('#remoteLoraSync').addEventListener('click',event=>{ const button=event.currentTarget; if(!confirm('从 5060 Ti 读取 LoRA 名称、附加信息和预览图？不会读取或复制模型文件。')) return; button.disabled=true; api('/api/remote-nodes/compute-5060ti/lora-catalog/sync',{method:'POST'}).then(()=>{ alert('更新任务已发送。可以回到“任务状态”查看进度。'); return loadTasks(); }).catch(error=>alert(error.message)).finally(()=>button.disabled=false); });
  $('#remoteModelSearch').addEventListener('submit',event=>{ event.preventDefault(); state.modelQuery=$('#remoteModelQuery').value.trim(); renderModels(); });
  $('#remoteModelTree').addEventListener('click',event=>{ const toggle=event.target.closest('[data-model-tree-toggle]'); if(toggle) { const key=toggle.dataset.modelTreeToggle; if(state.collapsedModelTypes.has(key)) state.collapsedModelTypes.delete(key); else state.collapsedModelTypes.add(key); renderModelTree(); return; } const filter=event.target.closest('[data-model-type]'); if(!filter) return; state.modelType=filter.dataset.modelType||''; state.modelFolder=filter.dataset.modelFolder||''; if(state.modelType) state.collapsedModelTypes.delete(state.modelType); renderModels(); });
  function clearModelFilters() { state.modelQuery=''; state.modelType=''; state.modelFolder=''; $('#remoteModelQuery').value=''; renderModels(); }
  $('#remoteModelClear').addEventListener('click',clearModelFilters);
  $('#remoteModelResetPath').addEventListener('click',clearModelFilters);
  $('#remoteModelSync').addEventListener('click',event=>{ const button=event.currentTarget; if(!confirm('从 5060 Ti 读取六类模型的名称、来源和同名示例图？不会读取或复制模型文件。')) return; button.disabled=true; api('/api/remote-nodes/compute-5060ti/model-catalog/sync',{method:'POST'}).then(()=>{ alert('更新任务已发送。可以回到“任务状态”查看进度。'); return loadTasks(); }).catch(error=>alert(error.message)).finally(()=>button.disabled=false); });
  $('#remoteTaskRefresh').addEventListener('click',()=>loadTasks().catch(console.error));
  $('#remoteTaskList').addEventListener('click',event=>{ const button=event.target.closest('[data-task-action]'); if(!button) return; const action=button.dataset.taskAction, taskId=button.dataset.taskId, nodeId=button.dataset.taskNode, base=`/api/remote-nodes/${encodeURIComponent(nodeId)}/tasks/${encodeURIComponent(taskId)}`; if(action==='retry'&&!confirm(`重新投递失败任务 ${taskId}？旧失败记录会保留。`)) return; if(action==='cancel'&&!confirm(`取消任务 ${taskId}？已开始的 ComfyUI 任务会请求中断。`)) return; button.disabled=true; const request=action==='integrity'?api(`${base}/integrity`):action==='import'?api(`/api/workflow-tasks/${encodeURIComponent(taskId)}/import-results`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({node_id:nodeId})}):action==='import-loras'?api(`${base}/import-lora-catalog`,{method:'POST'}):action==='import-models'?api(`${base}/import-model-catalog`,{method:'POST'}):api(`${base}/${action}`,{method:'POST'}); request.then(async result=>{ if(action==='integrity') alert(result.verified?`校验通过：${result.output_count} 个回传文件完整。`:`校验未通过：\n${(result.errors||[]).join('\n')}`); if(action==='import') alert(`已导入 ${result.image_count} 张图片${result.duplicates?`（${result.duplicates} 张已存在）`:''}${result.associated?'，并关联到原创作项目。':'。'}`); if(action==='import-loras') { alert(`已导入 ${result.count} 个 LoRA 条目，其中 ${result.with_preview_count||0} 个带视觉参照，共 ${result.preview_count||0} 张；权重未复制。`); await loadLoras($('#remoteLoraQuery').value.trim()); } if(action==='import-models') { alert(`已导入 ${result.count} 个模型资产，其中 ${result.with_preview_count||0} 个带示例图，共 ${result.preview_count||0} 张；权重未复制。`); await loadModels($('#remoteModelQuery').value.trim()); } return loadTasks(); }).catch(error=>alert(error.message)).finally(()=>button.disabled=false); });
  window.addEventListener('tag-language-change',renderLoras);
  window.ensureRemoteDevices=ensure;
})();
</script>
"""
