REMOTE_STYLES = r"""
<style>
  .remote-page { margin-top: 18px; }
  .remote-page[hidden] { display: none; }
  .remote-hero { display: grid; grid-template-columns: minmax(0,1.3fr) minmax(300px,.7fr); border: 1px solid var(--line); background: var(--paper); box-shadow: var(--shadow); }
  .remote-copy { min-height: 310px; padding: 46px; border-right: 1px solid var(--line); background: linear-gradient(130deg,transparent 0 72%,rgba(215,228,85,.38) 72%); }
  .remote-copy h1 { margin: 16px 0 12px; font: 800 clamp(50px,7vw,92px)/.84 "Iowan Old Style",serif; letter-spacing: -.055em; }
  .remote-copy p { max-width: 700px; color: var(--muted); line-height: 1.7; }
  .remote-boundary { padding: 34px; background: var(--ink); color: var(--paper); }
  .remote-boundary strong { display: block; margin: 14px 0; color: var(--acid); font: 800 24px "Iowan Old Style",serif; }
  .remote-boundary p { color: #aaa99f; font-size: 11px; line-height: 1.65; }
  .remote-grid { display: grid; grid-template-columns: 1fr; gap: 14px; margin-top: 14px; }
  .remote-card { border: 1px solid var(--line); background: var(--paper); padding: 22px; box-shadow: var(--shadow); }
  .remote-card-head { display: flex; justify-content: space-between; gap: 16px; align-items: start; }
  .remote-card h2 { margin: 4px 0 14px; font: 800 28px "Iowan Old Style",serif; }
  .remote-state { border: 1px solid var(--ink); background: var(--paper-deep); padding: 6px 8px; font: 900 8px monospace; }
  .remote-state.ready { background: var(--acid); }
  .remote-state.mount_missing, .remote-state.bridge_read_only { background: var(--signal); color: white; }
  .remote-form { display: grid; grid-template-columns: 1fr 1fr; gap: 9px; }
  .remote-form label { display: grid; gap: 6px; color: var(--muted); font: 800 8px monospace; text-transform: uppercase; }
  .remote-form label.wide { grid-column: 1/-1; }
  .remote-form input { min-width: 0; border: 1px solid var(--line); background: #fbf6ec; padding: 10px; }
  .remote-check { display: flex !important; align-items: center; grid-template-columns: auto 1fr; }
  .remote-check input { width: auto; }
  .remote-actions { display: flex; flex-wrap: wrap; gap: 7px; margin-top: 12px; }
  .remote-actions button { border: 1px solid var(--ink); background: transparent; padding: 9px 10px; font: 900 8px monospace; }
  .remote-actions button.primary { border-color: var(--signal); background: var(--signal); color: white; }
  .remote-message { min-height: 40px; margin-top: 12px; border-left: 4px solid var(--acid); background: #e2dccd; padding: 9px 11px; font: 8px/1.55 monospace; }
  .remote-tasks { margin-top: 14px; border: 1px solid var(--line); background: var(--paper); box-shadow: var(--shadow); }
  .remote-tasks-head { display: flex; justify-content: space-between; gap: 18px; align-items: end; padding: 22px; border-bottom: 1px solid var(--line); }
  .remote-tasks h2 { margin: 4px 0 0; font: 800 30px "Iowan Old Style",serif; }
  .remote-tasks-head button, .remote-task-card button { border: 1px solid var(--ink); background: transparent; padding: 9px; font: 900 8px monospace; }
  .remote-task-list { display: grid; grid-template-columns: repeat(3,minmax(0,1fr)); gap: 1px; background: var(--line); }
  .remote-task-card { min-width: 0; background: #f2ecdf; padding: 15px; }
  .remote-task-card strong, .remote-task-card span { display: block; overflow-wrap: anywhere; }
  .remote-task-card strong { margin: 7px 0; font: 800 14px "Iowan Old Style",serif; }
  .remote-task-card span { color: var(--muted); font: 8px/1.55 monospace; }
  .remote-task-state { width: fit-content; padding: 5px 7px; background: var(--paper-deep); color: var(--ink) !important; }
  .remote-task-state.completed, .remote-task-state.returned { background: var(--acid); }
  .remote-task-state.failed, .remote-task-state.canceled { background: var(--signal); color: white !important; }
  .remote-lora { margin-top: 14px; border: 1px solid var(--line); background: var(--paper); box-shadow: var(--shadow); }
  .remote-lora-head { display: flex; justify-content: space-between; gap: 18px; align-items: end; padding: 22px; border-bottom: 1px solid var(--line); }
  .remote-lora h2 { margin: 4px 0 0; font: 800 30px "Iowan Old Style",serif; }
  .remote-lora-search { display: flex; gap: 7px; }
  .remote-lora-search input { border: 1px solid var(--line); background: #fbf6ec; padding: 9px; }
  .remote-lora-tools { display: flex; flex-wrap: wrap; justify-content: end; gap: 7px; }
  .remote-lora-search button, .remote-lora-tools > button { border: 1px solid var(--ink); background: var(--ink); color: var(--paper); padding: 9px; font: 900 8px monospace; }
  .remote-lora-tools > button { background: var(--signal); border-color: var(--signal); }
  .remote-lora-search button.secondary { background: transparent; color: var(--ink); }
  .remote-lora-body { display: grid; grid-template-columns: 238px minmax(0,1fr); min-height: 390px; }
  .remote-lora-tree { border-right: 1px solid var(--line); background: #e7e0d2; padding: 16px 12px 22px; }
  .remote-lora-tree-title { display: flex; justify-content: space-between; gap: 8px; align-items: center; margin: 0 4px 12px; color: var(--muted); font: 900 8px monospace; text-transform: uppercase; letter-spacing: .08em; }
  .remote-lora-tree ul { margin: 0; padding: 0; list-style: none; }
  .remote-tree-root + .remote-tree-root { margin-top: 3px; }
  .remote-tree-row { display: grid; grid-template-columns: 22px minmax(0,1fr); gap: 3px; align-items: center; }
  .remote-tree-toggle, .remote-tree-filter { min-width: 0; border: 0; background: transparent; color: var(--ink); cursor: pointer; }
  .remote-tree-toggle { width: 22px; height: 27px; padding: 0; font: 900 10px monospace; }
  .remote-tree-filter { display: flex; justify-content: space-between; gap: 8px; width: 100%; padding: 7px 8px; text-align: left; font: 800 10px/1.2 monospace; }
  .remote-tree-filter:hover, .remote-tree-filter.active { background: var(--ink); color: var(--paper); }
  .remote-tree-filter span { overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
  .remote-tree-filter small { flex: 0 0 auto; color: inherit; font: 700 8px monospace; opacity: .65; }
  .remote-tree-all { grid-column: 1/-1; margin-bottom: 8px; }
  .remote-tree-children { margin: 2px 0 7px 25px !important; padding-left: 7px !important; border-left: 1px solid #aaa293; }
  .remote-tree-children[hidden] { display: none; }
  .remote-tree-children .remote-tree-filter { position: relative; padding: 6px 8px; font-size: 9px; }
  .remote-tree-children .remote-tree-filter::before { content: ''; position: absolute; left: -8px; top: 50%; width: 7px; border-top: 1px solid #aaa293; }
  .remote-lora-results { min-width: 0; }
  .remote-lora-result-head { display: flex; justify-content: space-between; gap: 14px; align-items: center; min-height: 45px; padding: 10px 15px; border-bottom: 1px solid var(--line); background: #f2ecdf; }
  .remote-lora-result-head p { margin: 0; color: var(--muted); font: 800 9px/1.5 monospace; }
  .remote-lora-result-head button { border: 0; border-bottom: 1px solid var(--ink); background: transparent; padding: 4px 0; font: 900 8px monospace; }
  .remote-lora-grid { display: grid; grid-template-columns: repeat(3,minmax(0,1fr)); gap: 1px; background: var(--line); }
  .remote-lora-card { min-width: 0; background: #f2ecdf; padding: 15px; }
  .remote-lora-preview { position: relative; display: block; width: calc(100% + 30px); aspect-ratio: 4/3; margin: -15px -15px 13px; overflow: hidden; border: 0; border-bottom: 1px solid var(--line); background: #d9d1c2; color: var(--muted); cursor: pointer; }
  .remote-lora-preview img { width: 100%; height: 100%; object-fit: cover; transition: transform .24s ease, filter .24s ease; }
  .remote-lora-preview:hover img { transform: scale(1.025); filter: contrast(1.04); }
  .remote-lora-preview-count { position: absolute; right: 9px; bottom: 9px; border: 1px solid rgba(255,255,255,.55); background: rgba(20,19,17,.82); color: white; padding: 5px 7px; font: 900 8px monospace; }
  .remote-lora-placeholder { display: grid; place-items: center; width: calc(100% + 30px); aspect-ratio: 4/3; margin: -15px -15px 13px; border-bottom: 1px solid var(--line); background: repeating-linear-gradient(135deg,#e4ddcf 0 9px,#ddd4c5 9px 10px); color: #8b8275; font: 900 8px monospace; letter-spacing: .08em; text-transform: uppercase; }
  .remote-lora-card h3 { margin: 0 0 8px; overflow-wrap: anywhere; font: 800 16px "Iowan Old Style",serif; }
  .remote-lora-card p { color: var(--muted); font: 8px/1.6 monospace; overflow-wrap: anywhere; }
  .remote-lora-breadcrumb { display: block; margin-bottom: 7px; color: var(--signal); font: 900 8px/1.4 monospace; text-transform: none; overflow-wrap: anywhere; }
  .remote-empty { grid-column: 1/-1; padding: 38px; text-align: center; }
  .remote-empty strong { display: block; font: 800 22px "Iowan Old Style",serif; }
  .remote-empty span { display: block; margin-top: 8px; color: var(--muted); font-size: 10px; }
  .remote-preview-dialog { width: min(1040px,calc(100vw - 32px)); max-height: calc(100vh - 32px); border: 1px solid var(--line); background: var(--paper); color: var(--ink); padding: 0; box-shadow: 14px 14px 0 rgba(20,19,17,.25); }
  .remote-preview-dialog::backdrop { background: rgba(20,19,17,.82); backdrop-filter: blur(3px); }
  .remote-preview-dialog-head { position: sticky; top: 0; z-index: 2; display: flex; justify-content: space-between; gap: 18px; align-items: center; border-bottom: 1px solid var(--line); background: var(--paper); padding: 15px 18px; }
  .remote-preview-dialog-head h3 { margin: 0; font: 800 24px "Iowan Old Style",serif; }
  .remote-preview-dialog-head p { margin: 3px 0 0; color: var(--muted); font: 800 8px monospace; }
  .remote-preview-dialog-head button { border: 1px solid var(--ink); background: var(--ink); color: var(--paper); padding: 9px 12px; font: 900 8px monospace; }
  .remote-preview-gallery { display: grid; grid-template-columns: repeat(2,minmax(0,1fr)); gap: 1px; background: var(--line); }
  .remote-preview-gallery a { min-width: 0; background: #ddd5c7; }
  .remote-preview-gallery img { display: block; width: 100%; height: min(62vh,680px); object-fit: contain; }
  @media (max-width: 1050px) { .remote-lora-grid, .remote-task-list { grid-template-columns: repeat(2,minmax(0,1fr)); } }
  @media (max-width: 820px) { .remote-lora-head { display: block; } .remote-lora-tools { display: grid; grid-template-columns: auto minmax(0,1fr); width: 100%; margin-top: 14px; } .remote-lora-search { display: grid; grid-template-columns: minmax(150px,1fr) auto auto; } }
  @media (max-width: 540px) { .remote-lora-body { grid-template-columns: 1fr; } .remote-lora-tree { border-right: 0; border-bottom: 1px solid var(--line); } }
  @media (max-width: 620px) { .remote-hero, .remote-grid, .remote-lora-grid, .remote-task-list, .remote-preview-gallery { grid-template-columns: 1fr; } .remote-copy { min-height: 0; padding: 30px 22px; border-right: 0; border-bottom: 1px solid var(--line); } .remote-boundary { padding: 24px 22px; } .remote-form { grid-template-columns: 1fr; } .remote-form label.wide { grid-column: auto; } .remote-lora-head, .remote-tasks-head { display: block; } .remote-lora-tools, .remote-lora-search { display: grid; grid-template-columns: 1fr; width: 100%; } .remote-lora-tools { justify-content: stretch; margin-top: 12px; } .remote-lora-search, .remote-tasks-head button { margin-top: 5px; } .remote-lora-result-head { align-items: start; } .remote-preview-gallery img { height: auto; max-height: 72vh; } }
</style>
"""

REMOTE_HTML = r"""
<section class="remote-page" id="remotePage" hidden>
  <section class="remote-hero"><div class="remote-copy"><span class="eyebrow">Windows compute bridge / one node</span><h1>设备<br>连接</h1><p>Mac 保存项目、审核、索引和任务状态；5060 Ti 运行 ComfyUI、其中的 LoRA Manager 插件，以及独立的 AnimaLoraStudio。当前 Worker 已完成 ComfyUI 出图与 LoRA 只读清单闭环；训练、VLM 与 Embedding 仍等待各自适配器。</p></div><aside class="remote-boundary"><span class="section-label">Security boundary</span><strong>这里只登记位置，不登记密码</strong><p>Windows 用户名与密码交给 macOS 钥匙串和 Finder 的 SMB 挂载。Prompt Hub 只记录设备角色、地址和 Mac 上已经挂载好的目录。</p></aside></section>
  <div class="remote-grid" id="remoteNodeGrid"></div>
  <section class="remote-tasks"><div class="remote-tasks-head"><div><span class="section-label">Mac task ledger / read & retry</span><h2>跨设备任务状态</h2><p>任务原始信封保留在 Mac；Windows 回传只进入待审核状态，不会自动改写项目。</p></div><button id="remoteTaskRefresh" type="button">刷新任务状态</button></div><div class="remote-task-list" id="remoteTaskList"></div></section>
  <section class="remote-lora"><div class="remote-lora-head"><div><span class="section-label">ComfyUI plugin metadata / read-only mirror</span><h2>ComfyUI LoRA 远程清单</h2><p id="remoteLoraStatus">正在读取 Windows LoRA 清单同步状态……</p></div><div class="remote-lora-tools"><button id="remoteLoraSync" type="button">从 Windows 同步</button><form class="remote-lora-search" id="remoteLoraSearch"><input id="remoteLoraQuery" placeholder="名称 / 路径 / trigger / 底模 / 标签"><button type="submit">检索清单</button><button class="secondary" id="remoteLoraClear" type="button">清除筛选</button></form></div></div><div class="remote-lora-body"><nav class="remote-lora-tree" aria-label="LoRA 目录树"><div class="remote-lora-tree-title"><span>Windows 文件夹</span><span>LoRA 数量</span></div><ul id="remoteLoraTree"></ul></nav><div class="remote-lora-results"><div class="remote-lora-result-head"><p id="remoteLoraResultStatus">正在整理目录……</p><button id="remoteLoraResetPath" type="button" hidden>返回全部目录</button></div><div class="remote-lora-grid" id="remoteLoraGrid"></div></div></div></section>
</section>
<dialog class="remote-preview-dialog" id="remotePreviewDialog"><div class="remote-preview-dialog-head"><div><h3 id="remotePreviewTitle">LoRA 视觉参照</h3><p id="remotePreviewMeta"></p></div><button id="remotePreviewClose" type="button">关闭</button></div><div class="remote-preview-gallery" id="remotePreviewGallery"></div></dialog>
"""

REMOTE_SCRIPT = r"""
<script>
(() => {
  const defaults=[{node_id:'compute-5060ti',label:'5060 Ti · 制图与炼丹节点',role:'compute_5060ti',capabilities:['comfyui_generate','workflow_test','result_metadata','wd14_batch','embedding_batch','vlm_caption_batch','lora_catalog_snapshot','lora_train','checkpoint_test']}];
  const state={nodes:[],catalog:[],loras:[],tasks:[],loraQuery:'',loraRoot:'',loraCategory:'',collapsedLoraRoots:new Set(),loraTreeReady:false};
  async function api(url,options={}) { const response=await fetch(url,options); const payload=await response.json().catch(()=>({})); if(!response.ok) throw new Error(payload.detail||`请求失败: ${response.status}`); return payload; }
  function combinedNodes() { return defaults.map(fallback=>({...fallback,...(state.nodes.find(item=>item.node_id===fallback.node_id)||{})})); }
  function nodeCard(node) { const mountPlaceholder='/Volumes/PromptHub-5060Ti'; return `<article class="remote-card" data-remote-node="${escapeHtml(node.node_id)}"><div class="remote-card-head"><div><span class="section-label">${escapeHtml(node.role)}</span><h2>${escapeHtml(node.label)}</h2></div><span class="remote-state" data-remote-state>未诊断</span></div><div class="remote-form"><label>主机名或局域网 IP<input data-node-field="host" value="${escapeHtml(node.host||'')}" placeholder="等待填写"></label><label>设备显示名<input data-node-field="label" value="${escapeHtml(node.label)}"></label><label class="wide">Mac 已挂载的 SMB 目录<input data-node-field="smb_mount" value="${escapeHtml(node.smb_mount||'')}" placeholder="${mountPlaceholder}"></label><label class="remote-check wide"><input data-node-field="enabled" type="checkbox" ${node.enabled?'checked':''}> 启用这台设备</label></div><div class="remote-actions"><button class="primary" data-remote-action="save">保存登记</button><button data-remote-action="diagnose">检查挂载</button><button data-remote-action="prepare">建立交付目录</button></div><div class="remote-message" data-remote-message>尚未配置。先在 Finder 挂载 5060 Ti 的 SMB，再填写这里。</div></article>`; }
  function renderNodes() { $('#remoteNodeGrid').innerHTML=combinedNodes().map(nodeCard).join(''); }
  function taskCard(item) { const labels={recorded:'Mac 已记录',queued:'等待领取',running:'Windows 执行中',returned:'结果待审核',completed:'已完成',failed:'失败',canceled:'已取消'}, retry=['failed','canceled'].includes(item.status)||['failed','canceled'].includes(item.result_status), actions=[]; if(retry) actions.push(`<button data-task-action="retry" data-task-id="${escapeHtml(item.task_id)}" data-task-node="${escapeHtml(item.node_id)}">重新投递</button>`); if(['queued','running'].includes(item.status)) actions.push(`<button data-task-action="cancel" data-task-id="${escapeHtml(item.task_id)}" data-task-node="${escapeHtml(item.node_id)}">取消任务</button>`); if(item.status==='returned') actions.push(`<button data-task-action="integrity" data-task-id="${escapeHtml(item.task_id)}" data-task-node="${escapeHtml(item.node_id)}">校验回传</button>`); if(item.status==='returned'&&item.result_status==='completed'&&item.task_type==='comfyui_generate') actions.push(`<button data-task-action="import" data-task-id="${escapeHtml(item.task_id)}" data-task-node="${escapeHtml(item.node_id)}">验收并导入图片</button>`); if(item.status==='returned'&&item.result_status==='completed'&&item.task_type==='lora_catalog_snapshot') actions.push(`<button data-task-action="import-loras" data-task-id="${escapeHtml(item.task_id)}" data-task-node="${escapeHtml(item.node_id)}">验收并导入 LoRA 清单</button>`); return `<article class="remote-task-card"><span class="remote-task-state ${escapeHtml(item.status)}">${escapeHtml(labels[item.status]||item.status)}</span><strong>${escapeHtml(item.task_type||'未知任务')}</strong><span>${escapeHtml(item.node_label)}<br>${escapeHtml(item.task_id)}<br>ATTEMPT / ${item.attempt||1}${item.worker_id?`<br>WORKER / ${escapeHtml(item.worker_id)}`:''}${item.error?`<br>ERROR / ${escapeHtml(item.error)}`:''}</span>${actions.join('')}</article>`; }
  function renderTasks() { $('#remoteTaskList').innerHTML=state.tasks.length?state.tasks.map(taskCard).join(''):'<div class="remote-empty"><strong>还没有跨设备任务</strong><span>启动 5060 Ti worker 后，从 Mac 投递的 ComfyUI、caption、embedding 和 LoRA 任务会显示在这里。</span></div>'; }
  function loraLocation(item) { const parts=String(item.relative_path||'').split('/').filter(Boolean); return {root:parts.length>1?parts[0]:'未分类',category:parts.length>2?parts[1]:'未分类'}; }
  function loraKey(value) { return String(value||'').trim().toLocaleLowerCase(); }
  function loraTreeData() { const roots=new Map(); state.catalog.forEach(item=>{ const location=loraLocation(item),rootKey=loraKey(location.root),categoryKey=loraKey(location.category); if(!roots.has(rootKey)) roots.set(rootKey,{key:rootKey,label:location.root,count:0,categories:new Map()}); const root=roots.get(rootKey); root.count+=1; if(!root.categories.has(categoryKey)) root.categories.set(categoryKey,{key:categoryKey,label:location.category,count:0}); root.categories.get(categoryKey).count+=1; }); return [...roots.values()].sort((a,b)=>a.label.localeCompare(b.label,'zh-CN',{numeric:true,sensitivity:'base'})).map(root=>({...root,categories:[...root.categories.values()].sort((a,b)=>a.label.localeCompare(b.label,'zh-CN',{numeric:true,sensitivity:'base'}))})); }
  function renderLoraTree() { const allActive=!state.loraRoot,tree=loraTreeData(); $('#remoteLoraTree').innerHTML=`<li class="remote-tree-row"><button class="remote-tree-filter remote-tree-all ${allActive?'active':''}" type="button" data-lora-root="" data-lora-category=""><span>全部 LoRA</span><small>${state.catalog.length}</small></button></li>`+tree.map(root=>{ const collapsed=state.collapsedLoraRoots.has(root.key),rootActive=state.loraRoot===root.key&&!state.loraCategory; return `<li class="remote-tree-root"><div class="remote-tree-row"><button class="remote-tree-toggle" type="button" data-lora-tree-toggle="${escapeHtml(root.key)}" aria-label="${collapsed?'展开':'收起'} ${escapeHtml(root.label)}" aria-expanded="${!collapsed}">${collapsed?'＋':'−'}</button><button class="remote-tree-filter ${rootActive?'active':''}" type="button" data-lora-root="${escapeHtml(root.key)}" data-lora-category=""><span>${escapeHtml(root.label)}</span><small>${root.count}</small></button></div><ul class="remote-tree-children" ${collapsed?'hidden':''}>${root.categories.map(category=>`<li><button class="remote-tree-filter ${state.loraRoot===root.key&&state.loraCategory===category.key?'active':''}" type="button" data-lora-root="${escapeHtml(root.key)}" data-lora-category="${escapeHtml(category.key)}"><span>${escapeHtml(category.label)}</span><small>${category.count}</small></button></li>`).join('')}</ul></li>`; }).join(''); }
  function loraCard(item) { const tags=(item.tags||[]).slice(0,12).map(tag=>window.displayCanonicalTag?.(tag)||tag),location=loraLocation(item),previews=item.preview_urls||[],visual=previews.length?`<button class="remote-lora-preview" type="button" data-lora-preview="${escapeHtml(item.lora_id)}" aria-label="查看 ${escapeHtml(item.name)} 的 ${previews.length} 张视觉参照"><img src="${escapeHtml(previews[0])}" alt="${escapeHtml(item.name)} 预览图" loading="lazy"><span class="remote-lora-preview-count">${previews.length} 张</span></button>`:'<div class="remote-lora-placeholder">暂无本地预览图</div>'; return `<article class="remote-lora-card">${visual}<span class="remote-lora-breadcrumb">${escapeHtml(location.root)} / ${escapeHtml(location.category)}</span><span class="section-label">${escapeHtml(item.model_family||'unknown')}</span><h3>${escapeHtml(item.name)}</h3><p>${escapeHtml(item.relative_path)}<br>BASE / ${escapeHtml(item.base_model||'未标注')}<br>TRIGGER / ${escapeHtml((item.trigger_words||[]).join(', ')||'未标注')}<br>TAGS / ${escapeHtml(tags.join(', ')||'未标注')}</p></article>`; }
  function filterLoras() { const needle=loraKey(state.loraQuery); state.loras=state.catalog.filter(item=>{ const location=loraLocation(item); if(state.loraRoot&&loraKey(location.root)!==state.loraRoot) return false; if(state.loraCategory&&loraKey(location.category)!==state.loraCategory) return false; if(!needle) return true; const searchable=[item.name,item.relative_path,item.base_model,item.model_family,...(item.trigger_words||[]),...(item.tags||[])].join(' ').toLocaleLowerCase(); return searchable.includes(needle); }); }
  function renderLoras() { filterLoras(); renderLoraTree(); const tree=loraTreeData(),root=tree.find(item=>item.key===state.loraRoot),category=root?.categories.find(item=>item.key===state.loraCategory),path=[root?.label,category?.label].filter(Boolean).join(' / ')||'全部目录',query=state.loraQuery?` · 搜索“${state.loraQuery}”`:''; $('#remoteLoraResultStatus').textContent=`${path}${query} · 当前 ${state.loras.length} / ${state.catalog.length} 个`; $('#remoteLoraResetPath').hidden=!state.loraRoot&&!state.loraQuery; $('#remoteLoraGrid').innerHTML=state.loras.length?state.loras.map(loraCard).join(''):state.catalog.length?'<div class="remote-empty"><strong>当前筛选没有结果</strong><span>可以切换左侧目录，或清除搜索条件。</span></div>':'<div class="remote-empty"><strong>还没有同步 ComfyUI LoRA 清单</strong><span>Windows 开机并运行 Worker 后，点击“从 Windows 同步”；Mac 只保存清单，不复制权重。</span></div>'; }
  async function loadNodes() { state.nodes=await api('/api/remote-nodes'); renderNodes(); }
  async function loadTasks() { const groups=await Promise.all(state.nodes.map(async node=>{ try { const tasks=await api(`/api/remote-nodes/${encodeURIComponent(node.node_id)}/tasks?limit=100`); return tasks.map(item=>({...item,node_id:node.node_id,node_label:node.label})); } catch(error) { return []; } })); state.tasks=groups.flat().sort((a,b)=>String(b.updated_at||b.created_at).localeCompare(String(a.updated_at||a.created_at))); renderTasks(); }
  async function loadLoras(query=state.loraQuery) { const status=await api('/api/windows-loras/status'); $('#remoteLoraStatus').textContent=status.available?`${status.count} 个 LoRA · ${status.with_preview_count||0} 个有视觉参照 · 共 ${status.preview_count||0} 张 · ${status.source_manager} · ${status.snapshot_id} · 权重不复制`:'尚未同步。保持 ComfyUI 与新版 Worker 运行，然后点击“从 Windows 同步”。'; const result=await api('/api/windows-loras?limit=500'); state.catalog=result.results||[]; state.loraQuery=query; if(!state.loraTreeReady) { loraTreeData().forEach(root=>{ if(root.key!=='anima') state.collapsedLoraRoots.add(root.key); }); state.loraTreeReady=true; } await window.ensureTagLabels?.(state.catalog.flatMap(item=>item.tags||[])); renderLoras(); }
  function openLoraPreviews(loraId) { const item=state.catalog.find(value=>value.lora_id===loraId),dialog=$('#remotePreviewDialog'); if(!item||(item.preview_urls||[]).length===0) return; $('#remotePreviewTitle').textContent=item.name; $('#remotePreviewMeta').textContent=`${item.relative_path} · ${(item.preview_urls||[]).length} 张本机缓存参照图`; $('#remotePreviewGallery').innerHTML=item.preview_urls.map((url,index)=>`<a href="${escapeHtml(url)}" target="_blank" rel="noreferrer" title="在新窗口打开原图"><img src="${escapeHtml(url)}" alt="${escapeHtml(item.name)} 视觉参照 ${index+1}" loading="lazy"></a>`).join(''); dialog.showModal(); }
  function payload(card,node) { return {label:card.querySelector('[data-node-field="label"]').value.trim(),role:node.role,host:card.querySelector('[data-node-field="host"]').value.trim(),smb_mount:card.querySelector('[data-node-field="smb_mount"]').value.trim(),enabled:card.querySelector('[data-node-field="enabled"]').checked,capabilities:node.capabilities||[],notes:''}; }
  async function act(card,action) { const nodeId=card.dataset.remoteNode,node=combinedNodes().find(item=>item.node_id===nodeId),message=card.querySelector('[data-remote-message]'),badge=card.querySelector('[data-remote-state]'); if(action==='save') { const saved=await api(`/api/remote-nodes/${encodeURIComponent(nodeId)}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload(card,node))}); state.nodes=state.nodes.filter(item=>item.node_id!==nodeId).concat(saved); message.textContent='设备位置已保存；未保存任何用户名或密码。'; return; } if(action==='prepare'&&!confirm('确认在已挂载的 SMB 目录中建立 prompt-hub/outbox、inbox、processing、completed、failed 五个文件夹？')) return; const endpoint=action==='prepare'?`/api/remote-nodes/${encodeURIComponent(nodeId)}/prepare`:`/api/remote-nodes/${encodeURIComponent(nodeId)}/diagnostics`, result=await api(endpoint,action==='prepare'?{method:'POST'}:{}); badge.textContent=result.worker_ready?'worker ready':result.state; badge.className=`remote-state ${result.state}`; message.textContent=result.worker_ready?`Windows worker 与本机 ComfyUI 已通过自检。PYTHON / ${result.worker_status?.python||'unknown'} · HOST / ${result.worker_status?.hostname||'unknown'}`:result.state==='ready'?'共享目录已就绪；等待 Windows 运行“1-先自检.bat”。':result.state==='mount_missing'?'Mac 还看不到这个 SMB 目录。请先在 Finder 连接服务器并挂载。':result.state==='mount_ready_bridge_unprepared'?'SMB 已挂载；可以建立五个交付目录。':result.state==='not_configured'?'尚未填写主机地址和 SMB 挂载路径。':`当前状态: ${result.state}`; }
  async function ensure() { await loadNodes(); await Promise.all([loadLoras(),loadTasks()]); }
  $('#remoteNodeGrid').addEventListener('click',event=>{ const button=event.target.closest('[data-remote-action]'); if(!button) return; const card=button.closest('[data-remote-node]'); button.disabled=true; act(card,button.dataset.remoteAction).catch(error=>card.querySelector('[data-remote-message]').textContent=error.message).finally(()=>button.disabled=false); });
  $('#remoteLoraSearch').addEventListener('submit',event=>{ event.preventDefault(); state.loraQuery=$('#remoteLoraQuery').value.trim(); renderLoras(); });
  $('#remoteLoraTree').addEventListener('click',event=>{ const toggle=event.target.closest('[data-lora-tree-toggle]'); if(toggle) { const key=toggle.dataset.loraTreeToggle; if(state.collapsedLoraRoots.has(key)) state.collapsedLoraRoots.delete(key); else state.collapsedLoraRoots.add(key); renderLoraTree(); return; } const filter=event.target.closest('[data-lora-root]'); if(!filter) return; state.loraRoot=filter.dataset.loraRoot||''; state.loraCategory=filter.dataset.loraCategory||''; if(state.loraRoot) state.collapsedLoraRoots.delete(state.loraRoot); renderLoras(); });
  $('#remoteLoraGrid').addEventListener('click',event=>{ const button=event.target.closest('[data-lora-preview]'); if(button) openLoraPreviews(button.dataset.loraPreview); });
  $('#remotePreviewClose').addEventListener('click',()=>$('#remotePreviewDialog').close());
  $('#remotePreviewDialog').addEventListener('click',event=>{ if(event.target===$('#remotePreviewDialog')) $('#remotePreviewDialog').close(); });
  function clearLoraFilters() { state.loraQuery=''; state.loraRoot=''; state.loraCategory=''; $('#remoteLoraQuery').value=''; renderLoras(); }
  $('#remoteLoraClear').addEventListener('click',clearLoraFilters);
  $('#remoteLoraResetPath').addEventListener('click',clearLoraFilters);
  $('#remoteLoraSync').addEventListener('click',event=>{ const button=event.currentTarget; if(!confirm('从 5060 Ti 扫描 LoRA 文件名、metadata 和预览？不会读取或复制权重内容。')) return; button.disabled=true; api('/api/remote-nodes/compute-5060ti/lora-catalog/sync',{method:'POST'}).then(result=>{ alert(`已投递 LoRA 清单任务：${result.task_id}`); return loadTasks(); }).catch(error=>alert(error.message)).finally(()=>button.disabled=false); });
  $('#remoteTaskRefresh').addEventListener('click',()=>loadTasks().catch(console.error));
  $('#remoteTaskList').addEventListener('click',event=>{ const button=event.target.closest('[data-task-action]'); if(!button) return; const action=button.dataset.taskAction, taskId=button.dataset.taskId, nodeId=button.dataset.taskNode, base=`/api/remote-nodes/${encodeURIComponent(nodeId)}/tasks/${encodeURIComponent(taskId)}`; if(action==='retry'&&!confirm(`重新投递失败任务 ${taskId}？旧失败记录会保留。`)) return; if(action==='cancel'&&!confirm(`取消任务 ${taskId}？已开始的 ComfyUI 任务会请求中断。`)) return; button.disabled=true; const request=action==='integrity'?api(`${base}/integrity`):action==='import'?api(`/api/workflow-tasks/${encodeURIComponent(taskId)}/import-results`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({node_id:nodeId})}):action==='import-loras'?api(`${base}/import-lora-catalog`,{method:'POST'}):api(`${base}/${action}`,{method:'POST'}); request.then(async result=>{ if(action==='integrity') alert(result.verified?`校验通过：${result.output_count} 个回传文件完整。`:`校验未通过：\n${(result.errors||[]).join('\n')}`); if(action==='import') alert(`已导入 ${result.image_count} 张图片${result.duplicates?`（${result.duplicates} 张已存在）`:''}${result.associated?'，并关联到原创作项目。':'。'}`); if(action==='import-loras') { alert(`已导入 ${result.count} 个 LoRA 条目，其中 ${result.with_preview_count||0} 个带视觉参照，共 ${result.preview_count||0} 张；权重未复制。`); await loadLoras($('#remoteLoraQuery').value.trim()); } return loadTasks(); }).catch(error=>alert(error.message)).finally(()=>button.disabled=false); });
  window.addEventListener('tag-language-change',renderLoras);
  window.ensureRemoteDevices=ensure;
})();
</script>
"""
