"""Directory browsing must reach Linux volumes and localized home folders.

Two Linux gaps: `browse_roots()` only knew macOS `/Volumes`, so a dataset on a second
disk (`/media/<user>`, `/run/media/<user>`, `/mnt`) was unreachable; and the home
shortcuts only matched English directory names, so a zh/ja desktop showed none.
"""

from __future__ import annotations

import sys
from pathlib import Path

import pytest

from prompt_hub import dataset_workspace
from prompt_hub.dataset_workspace import browse_roots, home_shortcuts

pytestmark = pytest.mark.skipif(sys.platform != "linux", reason="Linux volume layout")


@pytest.fixture(autouse=True)
def _no_xdg_config_override(monkeypatch: pytest.MonkeyPatch) -> None:
    """Keep user-dirs parsing anchored to the temp home, not the runner's config."""
    monkeypatch.delenv("XDG_CONFIG_HOME", raising=False)


def _write_user_dirs(home: Path, lines: list[str]) -> None:
    config = home / ".config"
    config.mkdir(parents=True, exist_ok=True)
    (config / "user-dirs.dirs").write_text("\n".join(lines) + "\n", encoding="utf-8")


def test_home_shortcuts_follow_xdg_user_dirs(tmp_path: Path) -> None:
    home = tmp_path / "home"
    for name in ("桌面", "图片", "下载"):
        (home / name).mkdir(parents=True)
    _write_user_dirs(
        home,
        [
            "# generated by xdg-user-dirs",
            'XDG_DESKTOP_DIR="$HOME/桌面"',
            'XDG_DOWNLOAD_DIR="$HOME/下载"',
            'XDG_PICTURES_DIR="$HOME/图片"',
        ],
    )

    shortcuts = home_shortcuts(home)
    labels = {label: path for path, label in shortcuts}
    assert labels["桌面"] == (home / "桌面").resolve()
    assert labels["图片"] == (home / "图片").resolve()
    assert labels["下载"] == (home / "下载").resolve()


def test_home_shortcuts_fall_back_to_english_names(tmp_path: Path) -> None:
    home = tmp_path / "home"
    (home / "Pictures").mkdir(parents=True)
    (home / "Downloads").mkdir()

    shortcuts = home_shortcuts(home)
    assert [path.name for path, _ in shortcuts] == ["Pictures", "Downloads"]


def test_home_shortcuts_mix_xdg_and_english_names(tmp_path: Path) -> None:
    home = tmp_path / "home"
    (home / "桌面").mkdir(parents=True)
    (home / "Downloads").mkdir()
    _write_user_dirs(home, ['XDG_DESKTOP_DIR="$HOME/桌面"'])

    shortcuts = home_shortcuts(home)
    # the configured entry takes the XDG name; the unconfigured one falls back to English
    assert [path.name for path, _ in shortcuts] == ["桌面", "Downloads"]


def test_home_shortcut_constants_keep_the_upstream_shape() -> None:
    shortcuts = dataset_workspace.BROWSE_HOME_SHORTCUTS
    # callers unpack (name, label); keep the shape we inherited from upstream
    assert all(isinstance(entry, tuple) and len(entry) == 2 for entry in shortcuts)
    # every shortcut needs an XDG key, otherwise it silently loses its localized name
    assert set(dataset_workspace.BROWSE_XDG_HOME_KEYS) == {name for name, _ in shortcuts}
    keys = dataset_workspace.BROWSE_XDG_HOME_KEYS.values()
    assert all(key.startswith("XDG_") for key in keys)


def test_home_shortcuts_skip_missing_directories(tmp_path: Path) -> None:
    home = tmp_path / "home"
    home.mkdir()
    assert home_shortcuts(home) == []


def test_volume_roots_skip_symlinks_and_duplicates(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    first = tmp_path / "mounts" / "disk-a"
    second = tmp_path / "mounts" / "disk-b"
    first.mkdir(parents=True)
    second.mkdir()
    (tmp_path / "mounts" / "loose-file").write_text("x", encoding="utf-8")
    (tmp_path / "second-base").mkdir()
    (tmp_path / "second-base" / "disk-a").symlink_to(first, target_is_directory=True)
    monkeypatch.setattr(
        dataset_workspace,
        "BROWSE_VOLUME_BASES",
        (tmp_path / "mounts", tmp_path / "second-base"),
    )

    roots = dataset_workspace._volume_roots()  # noqa: SLF001 - 内部函数是修复点本身
    assert roots == [first.resolve(), second.resolve()], "符号链接与重复项都要跳过"


def test_browse_roots_starts_with_home_and_includes_volumes(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    volume = tmp_path / "mounts" / "data"
    volume.mkdir(parents=True)
    monkeypatch.setattr(dataset_workspace, "BROWSE_VOLUME_BASES", (tmp_path / "mounts",))
    monkeypatch.setattr(dataset_workspace.Path, "home", classmethod(lambda _cls: tmp_path / "home"))

    roots = browse_roots()
    assert roots[0] == (tmp_path / "home").resolve()
    assert volume.resolve() in roots


def test_volume_bases_target_per_user_media_directories() -> None:
    bases = dataset_workspace._volume_bases()  # noqa: SLF001 - 断言 per-user 展开
    expected_user = Path.home().name
    assert Path(f"/media/{expected_user}") in bases
    assert Path(f"/run/media/{expected_user}") in bases
    assert Path("/mnt") in bases
